### ISSUE TITLE
urls generated with double slash

### ISSUE THREAD

**Issue by redzarf** [Dwolla/dwolla-php#50]
Thanks to the new logging in v2.1.0 I noticed that all of the endpoints have "/" at the start except 'token'.

Turns out that the urls being sent will have an extra slash added. For example MassPay->listJobs() results in the following being concatenated:

    $production_host = "https://www.dwolla.com/";
    $endpoint = "/masspay/";

Becoming: `https://www.dwolla.com//masspay/`

As far as I can see $customPostfix is only used by oauth which passes in $endpoint="token" without the slash.

I assume that the Dwolla webserver is handling the additional slashes, but it'd be worth tidying up some time.

**Comment by mach-kernel** [comment]
Since this is a cosmetic change I will group it in with 2.1.0

David Stancu

@mach-kernel <http://github.com/mach-kernel>

*Dwolla* / Developer Intern

On Feb 23, 2015, at 08:00, redzarf <notifications@github.com> wrote:

Thanks to the new logging in v2.1.0 I noticed that all of the endpoints
have "/" at the start except 'token'.

Turns out that the urls being sent will have an extra slash added. For
example in MassPay->listJobs() as the following are concatenated:

$production_host = "https://www.dwolla.com/";
$endpoint = "/masspay/";

Becoming: https://www.dwolla.com//masspay/

As far as I can see $customPostfix is only used by oauth which passes in
$endpoint="token" without the slash.

I assume that the Dwolla webserver is handling the additional slashes, but
it'd be worth tidying up some time.

—
Reply to this email directly or view it on GitHub
<https://github.com/Dwolla/dwolla-php/issues/50>.

**Comment by mach-kernel** [comment]
Hey @redzarf,

I just looked into this, I think you're forgetting about the `defaultPostfix` setting which gets appended to the host:

```php
public $default_postfix = 'oauth/rest';
```

Host + postfix + endpoint = `https://www.dwolla.com/oauth/rest/masspay`

I see no problem here?

**Comment by redzarf** [comment]
Ah, I see... in that case, I'd suggest a different change: that the 2 types of postfix have the slashes done consistently:

    public $default_postfix = 'oauth/rest';

and

    return self::_post('token', $params, 'oauth/v2/', false);

I'd suggest the custom postfix has the `/` taken off the end, and added onto the endpoint:

    return self::_post('/token', $params, 'oauth/v2', false);

Like you say, it's only a cosmetic change, but that'll be more consistent in the logging at least.

**Comment by mach-kernel** [comment]
That I can see! OK - awesome stuff. I just updated that and made the changes live :+1:
