### ISSUE TITLE
Include cacert.pem in guzzle client config

### ISSUE THREAD

**Issue by PrplHaz4** [Dwolla/dwolla-php#52]
I spent the morning chasing down
````
DwollaPHP: An error has occurred during a POST request.
DwollaPHP: An error has occurred; the response body is empty
DwollaPHP: Unable to create checkout due to API error.
````
which eventually traced to this in guzzle:
````
"cURL error 60: See http://curl.haxx.se/libcurl/c/libcurl-errors.html"
````

The 1.x version of the dwolla-php library included the certificate bundle (cacert.pem), and configured cURL to use it for requests.  Without it being configured, API requests will fail, but the real error is never conveyed to the user.

I was able to configure it at the apache level (thanks to http://stackoverflow.com/questions/21114371/php-curl-error-code-60), but this option will not be available to many users (thinking shared/managed host, probably more).  I'm thinking the best approach would be to include it in the default configuration as the 1.x version did (or at least mention the requirement in the readme).

**Comment by mach-kernel** [comment]
I apologize that this gave you grief, I expected that this wouldn't be an issue. Bundling a cacert bundle with the library is a bit unsafe in my mind, mainly because trusted certificate authorities change quite frequently with all the new exploits circulating out there. You are right though - it is in poor taste not to mention this in the readme. 

I have found a solution: The authors of CURL maintain a CA bundle [on their website](http://curl.haxx.se/ca/cacert.pem), so the latest can always be fetched from there. Does this sound like a good solution? Let me know what you think before I close this out.

**Comment by PrplHaz4** [comment]
That was the bundle I ended up using.  I agree, bundling it could be a concern (just was the obvious difference between the version that worked, and the one that didn't).

This issue plus the requirements in the readme should be good enough to help anyone that runs into the errors above (which don't obviously lead to a solution on their own).

:+1:
