### ISSUE TITLE
PHPDocs type-hinting doesn't match

### ISSUE THREAD

**Issue by fraserredmond** [Dwolla/dwolla-php#53]
The IDE I use is PhpStorm which uses PHPDoc style comments for class definitions.
http://phpdoc.org/docs/latest/references/phpdoc/tags/param.html

The dwolla-php comments define the `@param` data-types differently to the PHPDoc's definition, so they're not found at all.

For example, the params for this method:

    /**
     * Creates a MassPay job. Must pass in an array of items.
     *
     * @param $fundsSource {String} Funding Source for job.
     * @param $items {Array} Item array.
     * @param $params {Array} Additional parameters.
     *
     * @return null
     */
    public function create($fundsSource, $items, $params = false) {

should be changed to:

     * @param string $fundsSource Funding Source for job.
     * @param Item[] $items Item array.
     * @param array  $params Additional parameters.

That then lets the IDE recognise that `$params` is an array, instead of a boolean which it infers from the default value. (I'm not sure if there's an Item data-type, or if that ought to just be 'array'.)

**Comment by mach-kernel** [comment]
I also use IDEA but they show up for me! I'll take a look at what PHP
docstrings are supposed to look like and conform to those standards. Will
get a cosmetic fix out for this today!

David Stancu

@mach-kernel <http://github.com/mach-kernel>

*Dwolla* / Developer Intern

On Mar 4, 2015, at 04:10, redzarf <notifications@github.com> wrote:

The IDE I use is PhpStorm which uses PHPDoc style comments for class
definitions.
http://phpdoc.org/docs/latest/references/phpdoc/tags/param.html

The dwolla-php comments define the @param data-types differently to the
PHPDoc's definition, so they're not found at all.

For example, the params for this method:

/**
 * Creates a MassPay job. Must pass in an array of items.
 *
 * @param $fundsSource {String} Funding Source for job.
 * @param $items {Array} Item array.
 * @param $params {Array} Additional parameters.
 *
 * @return null
 */
public function create($fundsSource, $items, $params = false) {

should be changed to:

 * @param string $fundsSource Funding Source for job.
 * @param Item[] $items Item array.
 * @param array  $params Additional parameters.

That then lets the IDE recognise that $params is an array, instead of a
boolean which it infers from the default value. (I'm not sure if there's an
Item data-type, or if that ought to just be 'array'.)

—
Reply to this email directly or view it on GitHub
<https://github.com/Dwolla/dwolla-php/issues/53>.

**Comment by mach-kernel** [comment]
I apologize for being untimely, however, we have fixed this. Pull in version 2.1.2! 

Thanks again!

**Comment by fraserredmond** [comment]
Thanks! It wasn't exactly life-or-death :-)
