### ISSUE TITLE
oauth->get() is not working on localhost

### ISSUE THREAD

**Issue by j0hnw0rk3r** [Dwolla/dwolla-php#59]
Hi,

I setup a localhost test environment for Send transactions using the Dwolla OAuth library. 

I used this to generate auth url:

require_once('vendor/autoload.php');
use Dwolla\OAuth;

$redirect_uri = 'http://localhost/contractor/payments/dwolla/getAuthToken/';

function getAuthUrl() {
        $oauth = new OAuth();
        $auth_url = $oauth->getAuthUrl($redirect_uri);
        redirect($auth_url);
}

function getAuthToken() {
        $code = $_GET['code'];
        $oauth = new OAuth();
        $auth_token = $oauth->get($code, $redirect_uri);
        print_r($auth_token);
}

And the result in the print_r:
Array ( [error] => access_denied [error_description] => Redirect Uri does not match redirect uri associated with token. )

Please advise as I'm stuck on this for a day now.

**Comment by mach-kernel** [comment]
Hi @j0hnw0rk3r,

According to OAuth specification, your `redirect_uri` must match the redirect URL that you set in your application settings. Remember the place where you made your application on the Dwolla webpage? Go back to that same panel, and edit your application settings, then set the redirect url to the same one as in this snippet. 

Since this is not an issue related to the library I'm going to close out the issue. If you need support with the Dwolla API please post further inquiries to [our dedicated API support board](http://discuss.dwolla.com)
